
# =============================================
# Docker Compose Configuration for Tiệm Bánh
# Development Environment
# =============================================

version: '3.8'

services:
  # =============================================
  # MySQL Database Service
  # =============================================
  db:
    image: mysql:8.0
    container_name: tiembanh_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: qlchbn
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    networks:
      - app-network
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      timeout: 20s
      retries: 10
      interval: 30s

  # =============================================
  # Backend API Service
  # =============================================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tiembanh_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: qlchbn
      JWT_SECRET: dev_jwt_secret_key_for_development_only
      JWT_EXPIRES_IN: 24h
      CORS_ORIGIN: http://localhost:5173
      CORS_CREDENTIALS: true
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network

  # =============================================
  # Frontend Service
  # =============================================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tiembanh_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:5000/api
      VITE_APP_NAME: Quản Lý Tiệm Bánh
      VITE_DEV_MODE: true
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network

# =============================================
# Volumes
# =============================================
volumes:
  db_data:
    driver: local

# =============================================
# Networks
# =============================================
networks:
  app-network:
    driver: bridge